/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { QRCode } from "./components/zt-qr-scan/zt-qr-scan-types";
export namespace Components {
    interface ZtQrScan {
        "$canvas": HTMLCanvasElement;
        "$video": HTMLVideoElement;
        "hasCamera": () => Promise<boolean>;
        "hasFlash": () => Promise<any>;
        "height": number;
        "isFlashOn": () => Promise<boolean>;
        "pause": () => Promise<void>;
        "scanImage": (imageOrFileOrUrl: any, scanRegion?: any, canvas?: any) => Promise<void>;
        "setGrayscaleWeights": (red: number, green: number, blue: number, useIntegerApproximation?: boolean) => Promise<void>;
        "setInversionMode": (inversionMode: 'original' | 'invert' | 'both') => Promise<void>;
        "showCanvas": boolean;
        "showDetectedQR": boolean;
        "start": () => Promise<void>;
        "stop": () => Promise<void>;
        "toggleFlash": () => Promise<any>;
        "turnFlashOff": () => Promise<any>;
        "turnFlashOn": () => Promise<any>;
        "width": number;
    }
}
declare global {
    interface HTMLZtQrScanElement extends Components.ZtQrScan, HTMLStencilElement {
    }
    var HTMLZtQrScanElement: {
        prototype: HTMLZtQrScanElement;
        new (): HTMLZtQrScanElement;
    };
    interface HTMLElementTagNameMap {
        "zt-qr-scan": HTMLZtQrScanElement;
    }
}
declare namespace LocalJSX {
    interface ZtQrScan {
        "$canvas"?: HTMLCanvasElement;
        "$video"?: HTMLVideoElement;
        "height"?: number;
        "onCodeDetected"?: (event: CustomEvent<QRCode>) => void;
        "showCanvas"?: boolean;
        "showDetectedQR"?: boolean;
        "width"?: number;
    }
    interface IntrinsicElements {
        "zt-qr-scan": ZtQrScan;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "zt-qr-scan": LocalJSX.ZtQrScan & JSXBase.HTMLAttributes<HTMLZtQrScanElement>;
        }
    }
}
